-- MySQL Script generated by MySQL Workbench
-- Sun Jul  9 13:49:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema list_of_products
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `list_of_products` ;

-- -----------------------------------------------------
-- Schema list_of_products
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `list_of_products` DEFAULT CHARACTER SET utf8 ;
USE `list_of_products` ;

-- -----------------------------------------------------
-- Table `list_of_products`.`products_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `list_of_products`.`products_list` ;

CREATE TABLE IF NOT EXISTS `list_of_products`.`products_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `list_of_products`.`recipes_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `list_of_products`.`recipes_list` ;

CREATE TABLE IF NOT EXISTS `list_of_products`.`recipes_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `list_of_products`.`shop_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `list_of_products`.`shop_list` ;

CREATE TABLE IF NOT EXISTS `list_of_products`.`shop_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `list_of_products`.`step_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `list_of_products`.`step_list` ;

CREATE TABLE IF NOT EXISTS `list_of_products`.`step_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `step_nr` INT NOT NULL COMMENT 'step_number',
  `description` VARCHAR(128) NOT NULL,
  `recipes_list_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_step_list_recipes_list_idx` (`recipes_list_id` ASC) VISIBLE,
  CONSTRAINT `fk_step_list_recipes_list`
    FOREIGN KEY (`recipes_list_id`)
    REFERENCES `list_of_products`.`recipes_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `list_of_products`.`products_list_recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `list_of_products`.`products_list_recipe` ;

CREATE TABLE IF NOT EXISTS `list_of_products`.`products_list_recipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `qty` FLOAT NOT NULL COMMENT 'Quentity',
  `recipes_list_id` INT NOT NULL,
  `products_list_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_list_recipe_recipes_list1_idx` (`recipes_list_id` ASC) VISIBLE,
  INDEX `fk_products_list_recipe_products_list1_idx` (`products_list_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_list_recipe_recipes_list1`
    FOREIGN KEY (`recipes_list_id`)
    REFERENCES `list_of_products`.`recipes_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_list_recipe_products_list1`
    FOREIGN KEY (`products_list_id`)
    REFERENCES `list_of_products`.`products_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `list_of_products`.`recipes_list_shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `list_of_products`.`recipes_list_shop` ;

CREATE TABLE IF NOT EXISTS `list_of_products`.`recipes_list_shop` (
  `id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `shop_list_id` INT NOT NULL,
  `recipes_list_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recipes_list_shop_shop_list1_idx` (`shop_list_id` ASC) VISIBLE,
  INDEX `fk_recipes_list_shop_recipes_list1_idx` (`recipes_list_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipes_list_shop_shop_list1`
    FOREIGN KEY (`shop_list_id`)
    REFERENCES `list_of_products`.`shop_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipes_list_shop_recipes_list1`
    FOREIGN KEY (`recipes_list_id`)
    REFERENCES `list_of_products`.`recipes_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `list_of_products`.`products_list_shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `list_of_products`.`products_list_shop` ;

CREATE TABLE IF NOT EXISTS `list_of_products`.`products_list_shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `qty` FLOAT NOT NULL COMMENT 'Quentity',
  `products_list_id` INT NOT NULL,
  `shop_list_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_list_shop_products_list1_idx` (`products_list_id` ASC) VISIBLE,
  INDEX `fk_products_list_shop_shop_list1_idx` (`shop_list_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_list_shop_products_list1`
    FOREIGN KEY (`products_list_id`)
    REFERENCES `list_of_products`.`products_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_list_shop_shop_list1`
    FOREIGN KEY (`shop_list_id`)
    REFERENCES `list_of_products`.`shop_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
